### ISSUE TITLE
there a way to change.....

### ISSUE THREAD

**Issue by DrBlackross** [TeamWertarbyte/crypto-trading-bot#1]
if i changed the "BTC" side of things to a common name like "currency" in the code, then set it in the config it should trade that currency (eth, btc, usdt) in the bot as well as what was set in the...

 // BTC markets which the bot should watch out for
  markets: [
    'ZRX',

config section, right?

**Comment by DrBlackross** [comment]
ok change all BTC out and put in USDT... but i don't see it trading

**Comment by saschb2b** [comment]
I've completely rewrote the bot to use USDT now. It's also a config option now. Currently only `USDT` is tested. Hope that clears that up. If something new comes up feel free to reopen oder open a new ticket
