### ISSUE TITLE
readme.me mistake 2021.1.1

### ISSUE THREAD

**Issue by IHateNameStealers** [TeamWertarbyte/crypto-trading-bot#18]
In your **readme.md** you mention **./modules/configuration/types.ts**

> Adapt the config
> Change the configuration parameters to your liking config.json
> 
> For more details see the documentation in ./modules/configuration/types.ts

I think it should be  ./modules/configuration/Configuration.ts

**Comment by saschb2b** [comment]
Good catch thanks! Fixed
