### ISSUE TITLE
readme.me // await this.report(); 

### ISSUE THREAD

**Issue by IHateNameStealers** [TeamWertarbyte/crypto-trading-bot#19]
In your readme.md you mention  // await this.report(); 
This option has now been moved to the config.json file and should be changed in the readme.me

You need more coffee!

**Comment by saschb2b** [comment]
Thanks again! Yes, I really do. Will move most of this to the[ GitHub wiki](https://github.com/TeamWertarbyte/crypto-trading-bot/wiki) anyway so the readme will be much smaller. Will keep this ticket open until it's migrated.
