### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Summary' of undefined

### ISSUE THREAD

**Issue by engAhmad** [TeamWertarbyte/crypto-trading-bot#2]
![error-code](https://user-images.githubusercontent.com/5824594/82167778-7957d500-98c5-11ea-99c2-2bf0f5b14f74.png)

**Comment by IHateNameStealers** [comment]
2021. I know. It was coded 2 years ago. Old code.
Unfortunately I have exactly the same error.

**Comment by XENOTpro** [comment]
> 1. I know. It was coded 2 years ago. Old code.
>    Unfortunately I have exactly the same error.

I actually found the solution, if you remove some of the markets from config it works just fine! :)

**Comment by IHateNameStealers** [comment]
Removing some of markets did the trick!
Thank you.

**Comment by saschb2b** [comment]
Some markets made the old bot crash.  Returning an undefined object and proceed with that. The rewrite should ensure to only use active/usable markets. Will close this issue. If anything new comes up feel free to open a new ticket
