### ISSUE TITLE
FetchError: invalid json response body at https://api.bittrex.com/v3/balances/USDT

### ISSUE THREAD

**Issue by engAhmad** [TeamWertarbyte/crypto-trading-bot#35]
FetchError
invalid json response body at https://api.bittrex.com/v3/balances/USDT reason: Unexpected token < in JSON at position 0

I think its something related with **node_fetch** module 

[Sentry issue ](https://sentry.io/share/issue/437c70a2f2e44ab2a18fe21dcbb7e52b/)

**Comment by saschb2b** [comment]
@engAhmad thx for reporting and the linked sentry issue. This seems to be a duplicate of #13 I'll close this one for now. Further discussions will be made in the main issue.
