### ISSUE TITLE
Make ema steps customizable

### ISSUE THREAD

**Issue by saschb2b** [TeamWertarbyte/crypto-trading-bot#4]
Currently I've set EMA 9 and EMA 26 hard coded into the bot. 
By making them adjustable via the config more options should allow us to test any combination.

```
    const ema26 = ema()
      .id(0)
      .options({ windowSize: 26 })
      .merge((d: CandleReactStockCharts, c: number) => {
        d.ema26 = c;
      })
      .accessor((d: CandleReactStockCharts) => d.ema26);

    const ema9 = ema()
      .id(1)
      .options({ windowSize: 9 })
      .merge((d: CandleReactStockCharts, c: number) => {
        d.ema9 = c;
      })
      .accessor((d: CandleReactStockCharts) => d.ema9);
```

`windowSize` needs to be set by config.
Also `ema26` and `ema9` variable names need a more generic naming schema to prevent confusion.

**Comment by IHateNameStealers** [comment]
I think that this would be a nice option.
However. It would be even better if you can set this per crypto.
Different crypto > different  EMA strategy.

**Comment by saschb2b** [comment]
@IHateNameStealers good point. Thanks for the feedback.
As this is more like a global setting and your strategy seems more like an overwrite for specific markets, we could do both though.
The global setting is required anyway otherwise you would have to define every market.

Would you mind opening a new issue for that? I'll link it to this one then
