### ISSUE TITLE
Set EMA per market

### ISSUE THREAD

**Issue by IHateNameStealers** [TeamWertarbyte/crypto-trading-bot#7]
Not sure if this can be done, but it would be nice if the EMA S and L can be set per market.
Something like:

EMA 'BTC S=5 L=10', 'ETH S=3 L=11',

**Comment by saschb2b** [comment]
Related to #4

**Comment by saschb2b** [comment]
I decided while adding custom steps, also adding in custom ones for separat market would be a given.

Any feedback on the current implementation idea is welcome. -> #23
